Hotfix
- This fixes an error if the source url does not have a content length, it will redirect to using the backup url

File "C:\Users\David\Documents\GitHub\wco-dl\Downloader.py", line 68, in start_download
    with tqdm(unit='B', unit_scale=True, unit_divisor=1024, miniters=1, desc="Downloading", total=int(dlr.headers['content-length'], 0)) as pbar:
  File "C:\Users\David\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'